language: python
python:
- '2.7'
install:
- cd anarchoApp/
- python setup.py -q install
- anarcho init
- pip install coveralls
- cd ../
script:
  coverage run --source=anarcho -m unittest discover api_tests
after_success:
  coveralls

notifications:
  slack:
    secure: KrVZML0+7JPDfTCH/L8LF1MRZKfzmUA7LItlgHyLVOyp4qHPnU4Yz7e4XD878ngG/nQU5y863QsJQinAvYq6iIccnUk+UFb7/0W92nBWVANL/Mo6M/scnQrR0a70WlMKHGMAdQqSwmH93D7cxOMtiUS8zWCPS2lFHantZ31yx7I=
